version: '2'
services:
  sensors:
    image: migruiz/cameras-sensors-rpi3:r1
    container_name: cameras-sensors
    volumes:
     - camerasfs:/sys/fs/cgroup
    restart: always
    privileged: true
  heartbeat:
    image: migruiz/cameras-heartbeat-rpi3
    container_name: cameras-heartbeat
    volumes:
     - camerasfs:/sys/fs/cgroup
    restart: always
    privileged: true